[test] b07902001 徐維謙
amjltc295/PythonHomework pull request #34
Opened 2018-11-26 03:48 UTC by jameshwc

A Pull Request (PR) should explain why we need this PR and how you implement it, so others could understand it quickly.
Since this is just a homework, you do not need to explain why and how. 

**Do NOT change the status to NeedsReview if you do not want to be graded yet.**

Please fill in the following questions as feedback. It is totally optional and would not be graded.

## What is the most challenging part in this homework?

## Is this homework helpful for you?

## Is there any suggestion?

<br />  

#### PR readiness check list
> - [  ] Did it pass the Flake8 check?
> - [  ] Did you test this PR?  
> - [  ] Did you change the title of this PR to the correct format ([status] student_ID)?

2018-12-09 04:19 UTC, amjltc295 requested changes
Please include only your studentID.py in this PR. Also, it would be better to revise your commit message.

2018-12-11 12:50 UTC, amjltc295 approved these changes
You could choose not to change your code.

2018-12-11 12:50 UTC, amjltc295 commented on src/students/b07902001.py
> +    # TODO: download the image from img_url with the request module
Did you give up the task 8?

2018-12-11 14:17 UTC, jameshwc commented on src/students/b07902001.py
> +    # TODO: download the image from img_url with the request module
I have done it. Please check the Line 380 to Line 396. Thanks.

2018-12-11 14:20 UTC, amjltc295 approved these changes

2018-12-11 14:20 UTC, amjltc295 commented on src/students/b07902001.py
> +    def draw_text(
Please do not define draw_text() again as it is defined in utils.py. Import it and use it.

2018-12-11 14:20 UTC, amjltc295 commented on src/students/b07902001.py
> +    # TODO: download the image from img_url with the request module
@jameshwc okay, reviewed.

2018-12-11 16:35 UTC, jameshwc commented on src/students/b07902001.py
> +    def draw_text(
Done it. Please review. Thx.

2018-12-12 02:23 UTC, merged